// <auto-generated />
namespace CRUD_com_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class pessoa_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pessoa_email));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051935139_pessoa_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
