// <auto-generated />
namespace SistemaEscolar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SistemaEscolar3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SistemaEscolar3));
        
        string IMigrationMetadata.Id
        {
            get { return "202004272332533_SistemaEscolar3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
